CREATE TABLE IF NOT EXISTS author
(
    author_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar NOT NULL,
    surname   varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS book
(
    book_id          int GENERATED BY DEFAULT AS IDENTITY not null unique,
    title            varchar(255)                         not null unique,
    description      varchar(255),
    publication_date date DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS author_book
(
    author_id int REFERENCES author (author_id) ON DELETE CASCADE,
    book_id   int REFERENCES book (book_id) ON DELETE CASCADE,
    CONSTRAINT author_book_pkey PRIMARY KEY (author_id, book_id)
);

INSERT INTO author (name, surname)
VALUES ('Lev', 'Tolstoy'),
       ('J', 'Rowling');

INSERT INTO book (title, description)
VALUES ('Anna karenina', 'some good book'),
       ('детство', 'еще 1 книга Толстого'),
       ('Harry Potter', 'classic book'),
       ('1986', 'у нее нет автора в нашей табличке(((');

INSERT INTO author_book (author_id, book_id)
VALUES (1, 1),
       (1, 2),
       (2, 3);
